### ISSUE TITLE
Reason that extracting orbital labels is disabled for UPFv2?

### ISSUE THREAD

**Issue by dhroth** [simonpintarelli/upf_to_json#5]
When parsing a "version 1" UPF file (i.e. when using `upf1_to_json.py`), the result includes the orbital labels (e.g. "4S", "5D", etc.):
```
>>> ti_fn = "ti_pbe_v1.4.uspp.F.UPF"
>>> with open(ti_fn, "r") as f:
>>>     pp = upf_to_json(f.read(), fname=ti_fn)
>>> wfx = pp["pseudo_potential"]["atomic_wave_functions"]
>>> print(wfx[0].keys())
dict_keys(['label', 'angular_momentum', 'occupation', 'radial_function'])
```
However, when parsing a "version 2" UPF, no labels are returned:
```
>>> si_fn = "Si.pbe-n-rrkjus_psl.1.0.0.UPF"
...
>>> print(wfx[0].keys())
dict_keys(['radial_function', 'angular_momentum', 'occupation'])
```
It looks like this is because line 207 in `upf2_to_json.py` is commented out (as are lines 195 and 268). Is there a reason these lines are commented out? When I uncomment line 207 and run on all the pseudopotentials in the SSSP Efficiency set, I don't get any errors.

[ti_pbe_v1.4.uspp.F.UPF.txt](https://github.com/simonpintarelli/upf_to_json/files/14290868/ti_pbe_v1.4.uspp.F.UPF.txt)
[Si.pbe-n-rrkjus_psl.1.0.0.UPF.txt](https://github.com/simonpintarelli/upf_to_json/files/14290871/Si.pbe-n-rrkjus_psl.1.0.0.UPF.txt)

**Comment by dhroth** [comment]
(quick correction: I successfully get labels for `pp["pseudo_potential"]["atomic_wave_functions"]` if I un-comment line 268, not 207)

**Comment by simonpintarelli** [comment]
I'm not sure why it is commented. The scripts in this repository have been copied from [SIRIUS](https://github.com/electronic-structure/SIRIUS) to create a pip installable package for [aiida-core](https://github.com/aiidateam/aiida-core), such that aiida can create input files for SIRIUS. I assume the labels were commented because SIRIUS doesn't need them and probably there were some pseudos where labels have been missing.

I can make it optional, such that labels are silently skipped if they don't exist in the UPF file.

**Comment by simonpintarelli** [comment]
Labels are now added automatically if they exist
https://github.com/simonpintarelli/upf_to_json/pull/6

**Comment by dhroth** [comment]
Great! Appreciate you making the change
